updated test/index.js to extract DocumentFragment from linkedom and expose it to globalThis.
to FIX:
 uce@1.18.0 test
> c8 node test/index.js

/uce/node_modules/uhtml/cjs/persistent-fragment.js:32
class PersistentFragment extends custom(DocumentFragment) {
                                        ^

ReferenceError: DocumentFragment is not defined
    at Object.<anonymous> (/Users/simplebox/Desktop/test2/uce/node_modules/uhtml/cjs/persistent-fragment.js:32:41)
    at Module._compile (node:internal/modules/cjs/loader:1760:14)
    at Object..js (node:internal/modules/cjs/loader:1892:10)
    at Module.load (node:internal/modules/cjs/loader:1480:32)
    at Module._load (node:internal/modules/cjs/loader:1299:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.require (node:internal/modules/cjs/loader:1503:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/Users/simplebox/Desktop/test2/uce/node_modules/uhtml/cjs/handler.js:4:26)

Node.js v25.2.1